# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\"L\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61rticul\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"\x14\n\x12SendProductRequest\":\n\x13SendProductResponse\x12#\n\x08products\x18\x01 \x03(\x0b\x32\x11.products.Product2X\n\x08Products\x12L\n\x0bSendProduct\x12\x1c.products.SendProductRequest\x1a\x1d.products.SendProductResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=28
  _PRODUCT._serialized_end=104
  _SENDPRODUCTREQUEST._serialized_start=106
  _SENDPRODUCTREQUEST._serialized_end=126
  _SENDPRODUCTRESPONSE._serialized_start=128
  _SENDPRODUCTRESPONSE._serialized_end=186
  _PRODUCTS._serialized_start=188
  _PRODUCTS._serialized_end=276
# @@protoc_insertion_point(module_scope)
